import streamlit as st
import re
from llama_index.core import StorageContext, load_index_from_storage, Settings
from llama_index.llms.ollama import Ollama
from llama_index.embeddings.ollama import OllamaEmbedding
from llama_index.core.llms import ChatMessage
from duckduckgo_search import DDGS
from sentence_transformers import CrossEncoder

# --- PAGE CONFIG & DISCLAIMER ---
st.set_page_config(page_title="DE Residence Act Assistant", layout="wide")

st.title("🇩🇪 German Immigration Law Assistant")
st.warning(
    "⚠️ **DISCLAIMER:** This is a purely educational learning exercise and technical demonstration of a RAG system. "
    "The outputs are generated by AI, have not been verified by human experts, and **must not be taken as legal advice or professional opinion**. "
    "Do not rely on this tool for real-world immigration or legal decisions."
)

# --- SYSTEM PROMPT (module level — shared by RAG pipeline and future calls) ---
system_prompt = (
    "You are an assistant answering questions "
    "about German immigration and residence law. "
    "Your knowledge base covers three laws: "
    "AufenthG (applies to third-country nationals), "
    "FreizügG/EU (applies to EU citizens and their "
    "family members), and BeschV (employment permit "
    "approval requirements). "
    "Base your answers exclusively on the retrieved "
    "context. Begin every answer by stating which "
    "§§ you are drawing from. Quote the exact German "
    "text for every legal condition, then explain it "
    "in plain language. "
    "End every answer with: 'Please verify the "
    "source text in the panel below before relying "
    "on this for any decision.'"
)


# --- HELPER: extract explicit § references from user query ---
def extract_explicit_sections(query: str) -> list:
    """Return a list of § numbers explicitly named in the query (e.g. ['18b', '4a'])."""
    return re.findall(r'§\s*(\d+[a-z]*)', query, re.IGNORECASE)


# --- INITIALIZE AI (Cached so it loads instantly) ---
@st.cache_resource
def init_rag():
    # Setup LLM and Embedding Model
    Settings.llm = Ollama(model="qwen2.5:14b", request_timeout=300.0, additional_kwargs={"num_ctx": 8192})
    Settings.embed_model = OllamaEmbedding(
        model_name="nomic-embed-text-v2-moe",
        text_instruction="search_document: ",
        query_instruction="search_query: ",
    )

    # Load the database from the hard drive
    storage_context = StorageContext.from_defaults(persist_dir="./data_vector_store")
    index = load_index_from_storage(storage_context)

    reranker = CrossEncoder(
        "cross-encoder/ms-marco-MiniLM-L-6-v2",
        max_length=512
    )

    return reranker, index


reranker, index = init_rag()

# --- SIDEBAR SETTINGS ---
st.sidebar.header("📋 Example Topics")
st.sidebar.markdown("- *Was ist die Blaue Karte EU und wer ist berechtigt?*")
st.sidebar.markdown("- *What are the rules for a settlement permit for skilled workers?*")
st.sidebar.markdown("- *Welche Voraussetzungen gelten für den Familiennachzug?*")

# --- CHAT HISTORY MANAGEMENT ---
if "messages" not in st.session_state:
    st.session_state.messages = []
if "llm_history" not in st.session_state:
    st.session_state.llm_history = []

# Display chat messages from history on app rerun
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        # If there are sources attached to history, display them in an expander
        if "sources" in message and message["sources"]:
            with st.expander("📚 View Local Law Sources"):
                st.markdown(message["sources"])
        if "web_sources" in message and message["web_sources"]:
            with st.expander("🌐 View Web Sources"):
                st.markdown(message["web_sources"])

# --- CHAT INPUT & PROCESSING ---
use_internet = st.toggle("🌐 Enable Live Internet Search Fallback (Stage 2)", value=False, help="If checked, the AI searches the web if local laws don't answer the question fully.")

if prompt := st.chat_input("Ask a question about German residence status..."):

    # 1. Display user message
    st.chat_message("user").markdown(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})

    # 2. Generate and Display Assistant Response
    with st.chat_message("assistant"):
        with st.spinner("Consulting local immigration law database..."):

            # --- STAGE 1: RETRIEVE (top 20 candidates) ---
            retriever = index.as_retriever(similarity_top_k=20)
            retrieved_nodes = retriever.retrieve(prompt)

            # Priority boost: surface chunks from explicitly named §§ first
            explicit_sections = extract_explicit_sections(prompt)
            if explicit_sections:
                def section_priority(node):
                    sec = node.node.metadata.get("section", "")
                    for s in explicit_sections:
                        if s in sec:
                            return 0
                    return 1
                retrieved_nodes = sorted(retrieved_nodes, key=section_priority)

            # --- STAGE 2: RERANK (cross-encoder → top 5) ---
            if retrieved_nodes:
                pairs = [[prompt, node.node.get_content()] for node in retrieved_nodes]
                scores = reranker.predict(pairs)
                scored_nodes = sorted(
                    zip(scores, retrieved_nodes),
                    key=lambda x: x[0],
                    reverse=True
                )[:5]
                top_nodes = [node for _, node in scored_nodes]
            else:
                top_nodes = []

            # --- STAGE 3: GENERATE (inject context + conversation history) ---
            context_str = "\n\n---\n\n".join([n.node.get_content() for n in top_nodes])

            messages = [ChatMessage(role="system", content=system_prompt)]

            # Inject last 6 turns of conversation history for follow-up awareness
            for turn in st.session_state.llm_history[-6:]:
                messages.append(ChatMessage(role=turn["role"], content=turn["content"]))

            user_message_content = (
                f"Context from German law corpus:\n\n{context_str}\n\nQuestion: {prompt}"
            )
            messages.append(ChatMessage(role="user", content=user_message_content))

            llm_response = Settings.llm.chat(messages)
            local_answer = llm_response.message.content

            # Save this turn to conversation history
            st.session_state.llm_history.append({"role": "user", "content": user_message_content})
            st.session_state.llm_history.append({"role": "assistant", "content": local_answer})

            # Extract smart source citations using Regex
            sources_text = ""
            for node in top_nodes:
                snippet = node.node.get_content().strip()
                law = node.node.metadata.get("law", "AufenthG")

                # Only match § numbers in the heading area (first 150 chars) to avoid
                # false matches on § references inside body text
                match = re.search(r'(§\s*\d+[a-z]*)', snippet[:150])
                if match:
                    source_title = f"Legal Reference: {match.group(1)} {law}"
                else:
                    # Fallback if the chunk split cut off the header completely
                    preview = snippet.split('\n')[0][:40].replace('#', '').strip()
                    source_title = f"{law} Excerpt: {preview}..."

                short_snippet = snippet[:400] + "..."
                sources_text += f"**{source_title}**\n> {short_snippet}\n\n"

        final_answer = local_answer
        web_text = ""

        # 3. INTERNET SEARCH SYNTHESIS (Stage 2 - General Web Search)
        if use_internet:
            with st.spinner("Searching the live internet for recent context..."):
                try:
                    # Build a focused search query by stripping common stop-words
                    stop_words = {"what", "is", "the", "a", "an", "are", "how", "do",
                                  "i", "can", "for", "in", "of", "to", "and", "or"}
                    search_terms = [w for w in prompt.lower().split() if w not in stop_words]
                    search_query = " ".join(search_terms[:8]) + " Germany immigration law"

                    results = DDGS().text(search_query, max_results=3)

                    web_context = ""
                    for r in results:
                        web_context += f"- **{r['title']}**\n  {r['body']}\n\n"
                        web_text += f"**{r['title']}**\n{r['body']}\n[Link]({r['href']})\n\n"

                    synthesis_prompt = f"""
                    The user originally asked: "{prompt}"

                    1. The local German immigration law corpus (AufenthG, FreizügG/EU, BeschV) provided this context:
                    {local_answer}

                    2. A live internet search provided this recent context:
                    {web_context}

                    Please synthesize a final, highly professional answer. Combine the local legal rules with any relevant new context found on the internet.
                    CRITICAL: You MUST reply entirely in the same language as the user's original query ("{prompt}").
                    """
                    synthesized_response = Settings.llm.complete(synthesis_prompt)
                    final_answer = synthesized_response.text
                except Exception as e:
                    st.error(f"Internet search failed: {e}")
                    final_answer = local_answer + "\n\n*(Note: Internet search failed. Answer based solely on local documents).* "

        # 4. Print the final answer and Expanders to the screen
        st.markdown(final_answer)

        if sources_text:
            with st.expander("📚 View Local Law Sources"):
                st.markdown(sources_text)
        if web_text:
            with st.expander("🌐 View Web Sources"):
                st.markdown(web_text)

    # 5. Save the final response to chat history
    st.session_state.messages.append({
        "role": "assistant",
        "content": final_answer,
        "sources": sources_text,
        "web_sources": web_text
    })
